### Create Module
POST https://express-gateway-iu1f.onrender.com/modules_gateway/modules/add_module
Content-Type: application/json

{
  "mod_name": "Full Stack Devcscselopment",
  "mod_tech": "Python",
  "mod_duration": "2 monsccths"
}

### Get All Modules
GET https://express-gateway-iu1f.onrender.com/modules_gateway/modules/get_all_module

### Get Module by ID
GET https://express-gateway-iu1f.onrender.com/modules_gateway/modules/get_module_by_id/c85d768d-5adf-414b-a6b8-29fa712c9100
### Update Module
PUT https://express-gateway-iu1f.onrender.com/modules_gateway/modules/update_module
Content-Type: application/json

{
  "mod_id": "c85d768d-5adf-414b-a6b8-29fa712c9100",
  "mod_name": "Advanced Full Stack",
  "mod_tech": "python",
  "mod_duration": "8 months"
}

###  Delete Module
DELETE https://express-gateway-iu1f.onrender.com/modules_gateway/modules/delete_module/c85d768d-5adf-414b-a6b8-29fa712c9100

### Get Module Name by ID
GET https://express-gateway-iu1f.onrender.com/modules_gateway/modules/get_module_name_by_id/c85d768d-5adf-414b-a6b8-29fa712c9100

