### Create Organization
POST https://express-gateway-iu1f.onrender.com/organization_gateway/organization/create_org
Content-Type: application/json

{
  "org_name": "Muthayammaln University",
  "org_address": "Rasipuram",
  "org_email": "mec123@gmail.com",
  "org_contact": "456789098765",
  "org_associated_date": "2025-03-16"
}

### Get All Organizations
GET https://express-gateway-iu1f.onrender.com/organization_gateway/organization/get_all_org

### Get Organization by ID
GET https://express-gateway-iu1f.onrender.com/organization_gateway/organization/get_org_by_id/70051513-6ea6-466b-913f-721541a13066

### Update Organization
PUT https://express-gateway-iu1f.onrender.com/organization_gateway/organization/update_org_by_id
Content-Type: application/json

{
  "org_id": "70051513-6ea6-466b-913f-721541a13066",
  "org_name": " Muthayammal Deemed",
  "org_address": "Rasipuram",
  "org_email": "mec1368@gmail.com",
  "org_contact": "3456789098765",
  "org_associated_date": "2025-03-16",
  "mod_id": "70051513-6ea6-466b-913f-721541a13066"
}

### Delete Organization
DELETE https://express-gateway-iu1f.onrender.com/organization_gateway/organization/delete_org_by_id/70051513-6ea6-466b-913f-721541a13066

### GET Organization Name by MOD_ID
GET https://express-gateway-iu1f.onrender.com/organization_gateway/organization/get_org_name_by_id/70051513-6ea6-466b-913f-721541a13066