### Create User
POST https://express-gateway-iu1f.onrender.com/user_gateway/user/add_user
Content-Type: application/json

{
  "full_name": "mouleesh",
  "department": "Computer Science",
  "college": "mec",
  "rollno": "22ad085",
  "email": "moulee@gmail.com",
  "password": "0000",
  "status": "active",
  "user_last_login": "2025-03-16T10:00:00Z"
}

### Login User
POST https://express-gateway-iu1f.onrender.com/user_gateway/user/login
Content-Type: application/json

{
  "email": "dharun@gmail.com",
  "password": "0000"
}


### Get All Users
GET https://express-gateway-iu1f.onrender.com/user_gateway/user/read_all_users

### Get User by ID
GET https://express-gateway-iu1f.onrender.com/user_gateway/user/get_user_by_id/771b2715-fad9-407c-ada3-6232c5c7976b


### Update User
PUT https://express-gateway-iu1f.onrender.com/user_gateway/user/update_user/771b2715-fad9-407c-ada3-6232c5c7976b
Content-Type: application/json

{
  "full_name": "mouli",
  "email": "mouli@example.com",
  "password": "1234"
}

### Update User Last Login
PUT https://express-gateway-iu1f.onrender.com/user_gateway/user/update_last_login/b7062a63-5ed2-4ae6-b499-0bdcdda0d7fa
Content-Type: application/json

{
  "user_last_login": "2025-03-16T12:30:00Z"
}

### Delete User
DELETE https://express-gateway-iu1f.onrender.com/user_gateway/user/delete_user/771b2715-fad9-407c-ada3-6232c5c7976b


###############
GET https://express-gateway-iu1f.onrender.com/health

