### CREATE EXPERT
POST https://express-gateway-iu1f.onrender.com/expert_gateway/expert/add_expert
Content-Type: application/json

{
    "mod_expert_name": "moulee",
    "mod_expert_mobile": "9876543456789",
    "mod_expert_role": "Senior Developer",
    "mod_expert_profile": "https://example.com/profile.jpg"
}

### GET EXPERT
GET https://express-gateway-iu1f.onrender.com/expert_gateway/expert/read_all_experts

### GET EXPERT by mod_expert_id
GET https://express-gateway-iu1f.onrender.com/expert_gateway/expert/get_expert/081d3878-3c04-45cf-95e5-06c66eb62f26

###Update Expert by mod_expert_id
PUT https://express-gateway-iu1f.onrender.com/expert_gateway/expert/update_expert
Content-Type: application/json

{
    "mod_expert_id": "081d3878-3c04-45cf-95e5-06c66eb62f26",
    "mod_expert_name": "mouleesh",
    "mod_expert_mobile": "1234567898765",
    "mod_expert_role": "Lead Engineer",
    "mod_expert_profile": "https://example.com/new-profile.jpg",
    "poc_id": [],
    "mod_id": ["mod789"]
}


### Update poc_id separately by mod_expert_id 
PUT https://express-gateway-iu1f.onrender.com/expert_gateway/expert/update_poc
Content-Type: application/json

{
    "mod_expert_id": "081d3878-3c04-45cf-95e5-06c66eb62f26",
    "poc_id": ["poc123", "poc456"]
}

### Update mod_id separately by mod_expert_id 
PUT https://express-gateway-iu1f.onrender.com/expert_gateway/expert/update_mod
Content-Type: application/json

{
    "mod_expert_id": "081d3878-3c04-45cf-95e5-06c66eb62f26",
    "mod_id": ["6503caf1-fb75-4640-99f2-d6a529b71205"]
}

### Delete an Expert by mod_expert_id
DELETE https://express-gateway-iu1f.onrender.com/expert_gateway/expert/delete_expert/081d3878-3c04-45cf-95e5-06c66eb62f26

### GET EXPERT NAME BY MOD_ID
GET https://express-gateway-iu1f.onrender.com/expert_gateway/expert/get_expert_name/mod789


