### Create a new POC
POST https://express-gateway-iu1f.onrender.com/poc_gateway/poc/add_poc
Content-Type: application/json

{
    "mod_poc_name": "vijay",
    "mod_poc_role": "hod",
    "mod_poc_email": "vijay@gmail.com",
    "mod_poc_mobile": "7987654323456"
}

### Get all POCs
GET https://express-gateway-iu1f.onrender.com/poc_gateway/poc/read_all_poc

### Get POC by mod_poc_id
GET https://express-gateway-iu1f.onrender.com/poc_gateway/poc/get_poc_by_poc_id/13507cff-b220-496f-b656-a6970783953b

### Update POC details
PUT https://express-gateway-iu1f.onrender.com/poc_gateway/poc/update_poc
Content-Type: application/json

{
    "mod_poc_id": "13507cff-b220-496f-b656-a6970783953b",
    "mod_poc_name": "vijay",
    "mod_poc_role": "hod",
    "mod_poc_email": "vijay123@gmail.com",
    "mod_poc_mobile": "99981241887776",
    "mod_users": ["717150b2-2a19-45e8-9c24-69d93b4751c2"]
}

### Update only mod_tests and mod_users
PUT https://express-gateway-iu1f.onrender.com/poc_gateway/poc/update_mod_field
Content-Type: application/json

{
    "mod_poc_id": "13507cff-b220-496f-b656-a6970783953b",
    "mod_tests": [],
    "mod_users": ["717150b2-2a19-45e8-9c24-69d93b4751c2"]
}

### Update Test ID for a POC
PUT https://express-gateway-iu1f.onrender.com/poc_gateway/poc/update_test
Content-Type: application/json

{
    "mod_poc_id": "13507cff-b220-496f-b656-a6970783953b",
     "test_id": ["9eb93e29-0857-46e3-8ffd-7fe50249eab6"]
}

### Delete Test by mod_poc_id
DELETE https://express-gateway-iu1f.onrender.com/poc_gateway/poc/delete_test/13507cff-b220-496f-b656-a6970783953b
### Delete POC by mod_poc_id
DELETE https://express-gateway-iu1f.onrender.com/poc_gateway/poc/delete_poc/13507cff-b220-496f-b656-a6970783953b

###  GET POC BY USER
GET https://express-gateway-iu1f.onrender.com/poc_gateway/poc/mod_by_user/717150b2-2a19-45e8-9c24-69d93b4751c2

### GET MOD AND POC AND TEST ID BY USER ID 
GET https://express-gateway-iu1f.onrender.com/poc_gateway/poc/mod_and_poc/717150b2-2a19-45e8-9c24-69d93b4751c2


### GET MOD AND POC AND TEST ID BY USER ID 
GET https://express-gateway-iu1f.onrender.com/poc_gateway/poc/get_poc_certificate_by_mod_id/13507cff-b220-496f-b656-a6970783953b