### Create MCQ
POST https://express-gateway-iu1f.onrender.com/mcq_gateway/mcq/add_mcq
Content-Type: application/json

[
    {
        "mcq_question": "What is Express.js?",
        "mcq_options": ["Framework", "Library", "Runtime", "Database"],
        "mcq_answer": "Framework",
        "mcq_tag": ["Backend", "Node.js"]
    }
]

### Get All MCQs
GET https://express-gateway-iu1f.onrender.com/mcq_gateway/mcq/get_all_mcqs

### Get  MCQ  by id
GET https://express-gateway-iu1f.onrender.com/mcq_gateway/mcq/get_mcq/00b773d5-8b81-40e1-b232-76977d48f6f6

### Update MCQ  
PUT https://express-gateway-iu1f.onrender.com/mcq_gateway/mcq/update_mcq
Content-Type: application/json

{
    "mcq_id": "00b773d5-8b81-40e1-b232-76977d48f6f6",
    "mcq_question": "What is JavaScript?",
    "mcq_options": ["Runtime", "Library", "Framework", "Language"],
    "mcq_answer": "Language",
    "mcq_tag": ["Programming", "Frontend"]
}

### Delete MCQ
DELETE https://express-gateway-iu1f.onrender.com/mcq_gateway/mcq/delete_mcq/00b773d5-8b81-40e1-b232-76977d48f6f6


### Submit Result to External Service via Consul
POST https://express-gateway-iu1f.onrender.com/mcq_gateway/mcq/submit_result
Content-Type: application/json

{
  "result_user_id": "user_123123456787654",
  "result_test_id": "test_456",
  "result_score": 85,
  "result_total_score":100,  
  "result_poc_id": "poc_789",
  "result_id": "result_001"
}

#### GET MCQ ID ONLY
GET https://express-gateway-iu1f.onrender.com/mcq_gateway/mcq/mcq/ids