### Create Test
POST https://express-gateway-iu1f.onrender.com/test_gateway/test/create
Content-Type: application/json

{
    "test_name": "Sample Test",
    "test_language": "js",
    "test_total_score": 100,
    "test_mcq_id": [],
    "test_coding_id": []
}

### Get All Tests
GET https://express-gateway-iu1f.onrender.com/test_gateway/test/all

### Get Test by ID
GET https://express-gateway-iu1f.onrender.com/test_gateway/test/get_by_test_id/93056b90-f7ca-41d1-a892-db3407dd31e8

### Update Test (Add MCQ & Coding Test ID)
PUT https://express-gateway-iu1f.onrender.com/test_gateway/test/update
Content-Type: application/json

{
    "test_id": "93056b90-f7ca-41d1-a892-db3407dd31e8",
    "mcq_id":[
  "0453498a-cae3-4646-984a-098a9a0746de",
  "36d74197-1ee9-4f2b-98fe-58a45dde858a"
]
}

### Delete Test
DELETE https://express-gateway-iu1f.onrender.com/test_gateway/test/delete/93056b90-f7ca-41d1-a892-db3407dd31e8
Content-Type: application/json

### Remove MCQ from Test Using Test ID & MCQ ID
PUT https://express-gateway-iu1f.onrender.com/test_gateway/test/remove_mcq_from_test
Content-Type: application/json

{
    "test_id": "93056b90-f7ca-41d1-a892-db3407dd31e8",
    "mcq_id": "36d74197-1ee9-4f2b-98fe-58a45dde858a"
}


